name: Generar serpiente de contribuciones

on:
  schedule:
    - cron: "0 5 * * *"  # Diario 05:00 UTC (~00:00 en Colombia)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generar SVGs con Platane/snk
        uses: Platane/snk@v3
        with:
          github_user_name: nestorcastelblanco
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publicar en la rama output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
